name: Nuke Maui CI

on:
  push:
    branches: [ master ]
    paths:
      - "*.props"
      - "build/**"
      - "sample/**"
      - "src/**"
      - "version.json"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  build:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    permissions:
      statuses: write
      checks: write
    with:
      name: Nuke Maui
      solution-path: src/AvantiPoint.Nuke.Maui/AvantiPoint.Nuke.Maui.csproj
      run-tests: false
      code-sign: true
    secrets:
      codeSignKeyVault: ${{ secrets.CodeSignKeyVault }}
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}
      codeSignClientSecret: ${{ secrets.CodeSignClientSecret }}
      codeSignCertificate: ${{ secrets.CodeSignCertificate }}

  deploy-internal:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: build
    with:
      name: Deploy Internal
    secrets:
      feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      apiKey: ${{ secrets.IN_HOUSE_API_KEY }}
